#Arranging elements sequentially by row.  
P <- matrix(c(5:16), nrow = 4, byrow = TRUE)  
print(P)  
  
# Arranging elements sequentially by column.  
Q <- matrix(c(3:14), nrow = 4, byrow = FALSE)  
print(Q)  
  
# Defining the column and row names.  
row_names = c("row1", "row2", "row3", "row4")  
ccol_names = c("col1", "col2", "col3")  
  
R <- matrix(c(3:14), nrow = 4, byrow = TRUE, dimnames = list(row_names, col_names))  
print(R)  

In [1]:
 # Arithmetic operations on matrix :- 
# Add 2 matrix : row and columns of both matrix are same
# Substract of 2 matrix : row and columns of both matrix are same
# Multiplication of matrix
# 

In [2]:
# Create a first matrix A
V= 5 : 8
A = matrix(V,nrow=2,ncol=2,byrow=TRUE)
print(A)

     [,1] [,2]
[1,]    5    6
[2,]    7    8


In [5]:
# Create a B matrix
v = 1:4
B = matrix(v,nrow=2,ncol=2,byrow=TRUE)
print(B)

     [,1] [,2]
[1,]    1    2
[2,]    3    4


In [6]:
# Sum of 2 Matrix
print(A+B)

     [,1] [,2]
[1,]    6    8
[2,]   10   12


In [7]:
# Substract of 2 matrix
print(A- B)

     [,1] [,2]
[1,]    4    4
[2,]    4    4


In [9]:
# Multiply of 2 matrix
print(A*B)  # CROSS MULTIPLICATION

     [,1] [,2]
[1,]    5   12
[2,]   21   32


In [10]:
# Dot product or dot mulitplicaiton of 2 matirx
print(A%*%B)

# (5 X 1+ 3 X 6) = 23       (5 X 2 + 6 X 4) = 34
# (7 X 1 + 8 X 3) = 31      (7 X 2 + 8 X 4) = 46

     [,1] [,2]
[1,]   23   34
[2,]   31   46


In [13]:
# Transpose of matrix:
print(A)

     [,1] [,2]
[1,]    5    6
[2,]    7    8


In [17]:
# Transpose of A matrix then use inbuilt function t( matrix )
 t(A)


[,1] [,2]
[1,] 5    7   
[2,] 6    8

In [ ]:
#  